2025-07-13 12:44:08,708 INFO    MainThread:3783677 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-07-13 12:44:08,710 INFO    MainThread:3783677 [wandb_setup.py:_flush():67] Configure stats pid to 3783677
2025-07-13 12:44:08,710 INFO    MainThread:3783677 [wandb_setup.py:_flush():67] Loading settings from /home/sid/.config/wandb/settings
2025-07-13 12:44:08,710 INFO    MainThread:3783677 [wandb_setup.py:_flush():67] Loading settings from /home/sid/cosmo_compression/src/cosmo_compression/wandb/settings
2025-07-13 12:44:08,710 INFO    MainThread:3783677 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-07-13 12:44:08,710 INFO    MainThread:3783677 [wandb_init.py:setup_run_log_directory():662] Logging user logs to ./wandb/run-20250713_124408-vdxsesxq/logs/debug.log
2025-07-13 12:44:08,710 INFO    MainThread:3783677 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to ./wandb/run-20250713_124408-vdxsesxq/logs/debug-internal.log
2025-07-13 12:44:08,710 INFO    MainThread:3783677 [wandb_init.py:init():781] calling init triggers
2025-07-13 12:44:08,710 INFO    MainThread:3783677 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-07-13 12:44:08,710 INFO    MainThread:3783677 [wandb_init.py:init():809] starting backend
2025-07-13 12:44:08,710 INFO    MainThread:3783677 [wandb_init.py:init():813] sending inform_init request
2025-07-13 12:44:08,714 INFO    MainThread:3783677 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-07-13 12:44:08,714 INFO    MainThread:3783677 [wandb_init.py:init():823] backend started and connected
2025-07-13 12:44:08,715 INFO    MainThread:3783677 [wandb_init.py:init():915] updated telemetry
2025-07-13 12:44:08,719 INFO    MainThread:3783677 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-07-13 12:44:09,187 INFO    MainThread:3783677 [wandb_init.py:init():1014] starting run threads in backend
2025-07-13 12:44:09,272 INFO    MainThread:3783677 [wandb_run.py:_console_start():2454] atexit reg
2025-07-13 12:44:09,272 INFO    MainThread:3783677 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-07-13 12:44:09,272 INFO    MainThread:3783677 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-07-13 12:44:09,272 INFO    MainThread:3783677 [wandb_run.py:_redirect():2394] Redirects installed.
2025-07-13 12:44:09,273 INFO    MainThread:3783677 [wandb_init.py:init():1056] run started, returning control to user process
2025-07-13 12:44:09,274 INFO    MainThread:3783677 [wandb_run.py:_config_callback():1327] config_cb None None {'output_dir': '', 'root': '/monolith/global_data/astro_compression/CAMELS', 'run_name': 'final_test', 'camels_suite': 'Astrid', 'camels_data': 'LH', 'learning_rate': 5e-05, 'grad_clip': 1.0, 'batch_size': 8, 'accumulate_gradients': None, 'num_workers': 4, 'save_every': 50, 'eval_every': 50, 'latent_dim': 256, 'latent_img_channels': 8, 'train_size': 14000, 'val_size': 1000, 'max_steps': 2000, 'max_epochs': 100, 'profile': False, 'gpus': 6, 'use_wandb': True}
2025-07-13 12:44:34,273 INFO    MainThread:3783677 [wandb_run.py:_config_callback():1327] config_cb None None {'unconditional': False, 'log_wandb': True, 'reverse': False, 'latent_img_channels': 8}
2025-07-13 13:05:30,295 INFO    MsgRouterThr:3783677 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-07-13 13:05:31,177 ERROR   MainThread:3783677 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-13 13:05:31,178 ERROR   MainThread:3783677 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/sid/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
